### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by cesaraaron** [bentx/vscode-custom-theme#2]
- Win 10 latest insider build.
- Vscode 1.8.0.
- Runned in admin mode with only the theme (atom one dark) and this extension activated with no custom preferences or keybindings.

When I apply the custom theme it reloads but nothing changes.
What do you think is happening?

**Comment by bentx** [comment]
If it reloads, it means there isn't any issue with the patching of VS code. Have you modified any of the default settings in your user settings (see readme for how-to) ? Could you provide a screenshot of it ?

**Comment by bentx** [comment]
Actually since you mentioned "with no custom preferences", I guess that's the issue. Search for "custom theme" in your default settings, pick any of the option here, let's say `"theme.statusbar.background.color": "#007acc"` and paste it in your user settings like this `"theme.statusbar.background.color": "#f00"` and you should now have a red status bar.

**Comment by cesaraaron** [comment]
Well yes, that was the `problem` sorry.
I close this.
