### ISSUE TITLE
Why not hide feedback smiley icon completely?

### ISSUE THREAD

**Issue by rfgamaral** [bentx/vscode-custom-theme#8]
Why not use `display: none;` instead of `display:inline-block;opacity:0;` for `.statusbar-item>.dropdown.send-feedback`?

**Comment by bentx** [comment]
Good question ! I guess the idea was to not kill the feature, I think the quick links to "Submit a bug" or "Request a missing feature" are nice to have there (especially since they are pre-templating the message for you with useful data), so playing with opacity just removes the smiley face some people find distracting, while keeping all that available.

**Comment by rfgamaral** [comment]
Yeah, I don't like the smiley face either but that wasted space when it's off also bothers me lol. Perhaps introduce a third option to completely hide it? Just a suggestion :)

**Comment by bentx** [comment]
Sure, feel free to submit a PR !
